name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    if: github.repository == 'guangzan/tona'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set node version to 20
        uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build packages
        run: pnpm build:pkg

      - name: Publish to npm
        run: npm i -g npm@^11.5.2 && pnpm run publish-ci ${{ github.ref_name }}

      - name: Generate Changelog
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
